server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: tian3218
  data:
    redis:
#      服务器地址
      host: localhost
#      redis服务器端口
      port: 6379
#      密码
      password:
#        连接超时时间
      timeout: 5000ms
#      数据库索引 0-15 默认是0
      database: 0
#      连接池配置 使用lettuce
      lettuce:
        pool:
#          连接池最大连接数
          max-active: 200
#          最大空闲连接
          max-idle: 10
#          连接池最大等待时间，负数表示没有限制
          max-wait: -1ms
#          连接池中最小空闲连接
          min-idle: 0
#          空闲连接检测中期
          time-between-eviction-runs: 60s

codertqy:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c4019918e2cceb1f3b
      accountToken: d0c4aacf5f2149cfa42563ed6a7b02c1
      appId: 2c94811c9860a9c4019918e2ce671f42
      templateId: 1